### ISSUE TITLE
How to Use This?

### ISSUE THREAD

**Issue by Jacksonmbower** [FUE5BASE/FUE5#5]
I'm unaware if it is just me but the need to know section is either unclear or completely missing parts as I have no idea what I am doing trying to get this working. I am not particularly knowledgeable in using unreal engine but either way it seems like there is missing information in the documentation.

**Comment by FluffyDiscord** [comment]
This should be all you need to know https://github.com/FUE5BASE/FUE5#what-you-need-to-know-to-run-this-project
